name: GitHub - Activity - Readme

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/recent-activity@v2.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}

